<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1559032009543" stop="1559032009543">
  <description>This is the tests collection phase. Failures are modules that failed to collect.</description>
  <name>test_collection_phase</name>
  <title>Collection phase</title>
  <labels/>
  <test-cases>
    <test-case start="1559032009543" status="broken" stop="1559032009543">
      <name>test_login</name>
      <failure>
        <message>failed</message>
        <stack-trace>test_login.py:31: in &lt;module&gt;
    print(get_login_data())
test_login.py:19: in get_login_data
    login_data = GetFileData().get_yaml_data("logindata.yml")
..\Base\getfiledata.py:18: in get_yaml_data
    with open(file_path, "r") as f:
E   FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\86156\\Desktop\\APP\\APP_day009\\scripts\\Data\\logindata.yml'</stack-trace>
      </failure>
      <attachments/>
      <labels/>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
